### ISSUE TITLE
Can't login sometimes

### ISSUE THREAD

**Issue by kadaradam** [Southclaw/ScavengeSurvive#248]
So sometimes after the server automatically restarts players can't login. I think the problem is with the y_inline initalizing, because the Login() function is not called, after you type the password. I guess this is because the dialog does not even give response.

```
[05/06/2016 12:21:39] [join] Markus_Aurelius has joined the server (0::1)
[05/06/2016 12:21:39] INFO: [RemoveObjects_FirstLoad] Created session data for Markus_Aurelius
[05/06/2016 12:21:39] [JOIN] Markus_Aurelius joined
[05/06/2016 12:21:44] [LOAD] Markus_Aurelius (account exists, prompting login) Alive: 1 Last login: Sunday Jun 05 2016 at 11:04:05
[05/06/2016 12:21:44] [LOGPROMPT] Markus_Aurelius is logging in
[05/06/2016 12:21:56] INFO: [OnPlayerDisconnect] Removing session data file for Markus_Aurelius
[05/06/2016 12:21:56] [LOGOUT] Markus_Aurelius not logged in.
[05/06/2016 12:21:56] [part] Markus_Aurelius has left the server (0:1)
```

**Comment by Southclaw** [comment]
Could this be happening because DisplayLoginPrompt is displayed before some internal y_inline initialisation function? If so, it shouldn't really happen because of the 5s delay on `LoadAccountDelay` inside `/player/core.pwn`. I may have to remove y_inline completely if this becomes an ongoing problem.

I don't really know enough about y_inline's internals to know what it requires to work.

**Comment by kadaradam** [comment]
I don't think that's the problem, because the only way to fix this issue is to kill the server and start it again. Even relog won't help.

**Comment by kadaradam** [comment]
It happend again today. I checked, and non of the dialogs work. So the preoblem should be with y_inline.

**Comment by Southclaw** [comment]
Right, looks like it's time to fall back to a dialog callback hook.

**Comment by PT-Player** [comment]
@Y_Less take an looke here maybe you got some ideas to fix it..

**Comment by XFlawless1** [comment]
It's back again aswell, if you do a manual restart,, /gmx or /rcon gmx instantly either /restart 0
It won't let your players login
It back on https://github.com/Southclaw/ScavengeSurvive/commit/ab1c2b249d6bdccdd72dae68f62961f08a46ee68

**Comment by Y-Less** [comment]
I'm sure that this is the same as:

https://github.com/Misiur/YSI-Includes/issues/99
https://github.com/Misiur/YSI-Includes/issues/91
https://github.com/Misiur/YSI-Includes/issues/62

I think there might be enough information between those to be able to do something about it now.  I'm still not 100% sure what the issue is; however, I MIGHT have an idea.  I simply couldn't do much about it before because I had never seen the problem and everyone who had didn't provide enough information to reproduce it.  But between them, I think the information is now there.

**Comment by PT-Player** [comment]
And with this too: https://github.com/Misiur/YSI-Includes/issues/45


@Y-Less can say what You Think it is?

**Comment by Y-Less** [comment]
No, https://github.com/Misiur/YSI-Includes/issues/45 is a separate issue, to do with the fact that normal dialogs have their IDs given expicitly, while y_dialog abstracts and hides that information.  My theory is that the issue is to do with the way that y_malloc allocates heap space.  Previously, y_malloc assigned memory from a huge global array, but people would complain about the massive compile times and file sizes - even though it was all fine IMHO.  So now, instead it uses `#pragma dynamic` to allocate a huge stack/heap size, which isn't included in the compiled file but instead created by the VM on start.  It then uses a bug in the VM to move the heap pointer up a long way and fix it there - real heap uses will thus never see this "hidden" part and allocations can be safely made in this space:

https://github.com/Misiur/YSI-Includes/blob/f1b57c293a09a9f3c43e36f6b6cf7798efb5f45c/YSI_Coding/y_malloc/heapalloc.inc#L367-L394

Of course, using bugs is never the best thing to do, I think it might actually be somehow re-using or confusing the heap spaces of multiple reloaded scripts, because it doesn't know that it can't; and will always assume that the heap is garbage on mode start, while to y_malloc it looks like real data.  I've not fully worked out exactly how this can happen or what the results would be, but if so, it would mean that all previously made allocations would still be there, with new ones coming from a smaller and smaller pool of memory.

For reference, the bug can be seen here, and was fixed in later versions of the VM than the one used in SA:MP (if you want old PAWN implementations: http://y-less.com/uploads/PAWN.rar).  I'm actually struggling to remember what it was, but I'm pretty sure it was to do with calling `OP_HALT` not correctly saving and restoring a heap pointer after another call.

Old `OP_HALT`:

```c
  op_halt:
    GETPARAM(offs);
    if (retval!=NULL)
      *retval=pri;
    /* store complete status (stk and hea are already set in the ABORT macro) */
    amx->frm=frm;
    amx->pri=pri;
    amx->alt=alt;
    amx->cip=(cell)((unsigned char*)cip-code);
    if (offs==AMX_ERR_SLEEP) {


      amx->reset_stk=reset_stk;
      amx->reset_hea=reset_hea;
      return (int)offs;
    } /* if */
    ABORT(amx,(int)offs);
```

New `OP_HALT`:

```c
  op_halt:
    GETPARAM(offs);
    if (retval!=NULL)
      *retval=pri;
    /* store complete status (stk and hea are already set in the ABORT macro) */
    amx->frm=frm;
    amx->pri=pri;
    amx->alt=alt;
    amx->cip=(cell)((unsigned char*)cip-code);
    if (offs==AMX_ERR_SLEEP) {
      amx->stk=stk;
      amx->hea=hea;
      amx->reset_stk=reset_stk;
      amx->reset_hea=reset_hea;
      return (int)offs;
    } /* if */
    ABORT(amx,(int)offs);
```

The calls to `SCTRL` and `SYSREQ.C` in my code have the effect of moving the current heap, frame, and stack pointers in to the VM.  The stack pointer needs some work because `SYSREQ.C` has parameters that adjust the stack, so `RETN` stores the stack.  Then `HALT 12` is called, which is equivalent to `sleep()`, but that does nothing in non-main functions except end them instantly.  When the next public is called, it isn't a `sleep` resume because we weren't in main, and the restore parameters are replaced with the modified heap.  Actually, I just realised that the bug is irrelevant between the two `OP_HALT` versions - in fact the extra calls are to work around the bug.  The issue comes from modifying the heap, then calling `sleep()`, but never resuming, and so never restoring the heap.

**Comment by PT-Player** [comment]
I Think the problem of https://github.com/Misiur/YSI-Includes/issues/45 is caused nu this too. 

Anyway that explain Why in ysi 3.1 dont happends this bug

**Comment by Y-Less** [comment]
I really don't - the symptoms are nothing alike.

**Comment by Southclaw** [comment]
That might explain why I've never come across this actually, when I ran a server on linux last year I had to [crash the server](https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/ScavengeSurvive.pwn#L716) to restart it in order to fix a bug in another plugin so the server never gmx'd it always started from scratch.

**Comment by Y-Less** [comment]
My big explanation was actually useless, since I realised right at the end that what I had always remembered as being the enabler for y_malloc was actually a bug I had to fix to make the real enabler work.  Ignore everything I said about `OP_HALT`'s bug!  The code should be something like:

```pawn
hook OnScriptInit()
{
    SetTimer("Malloc_Solidify", 0, 0);
    SetTimer("Malloc_Solidify", 0, 0);
}

public Malloc_Solidify()
{
    #emit HEAP <huge_number>
    sleep();
}
```

Which will cause `sleep` to get called twice without ever resuming (since public functions aren't resumed).  That means that first time stores the current heap locations, second time stores that stored heap location to the "restore heap" location, and then all subsequent public functions have the new heap location fully ingrained in to themselves and cannot possibly restore the original.  I use `#emit HALT 12` because that is what `sleep()` truly is, but that is better when dealing with assembly.  All the other assembly in that function just fixes a bug in `OP_HALT` that was fixed correctly in later AMX versions, but not in SA:MP.

**Comment by Y-Less** [comment]
I don't know what the best source for fixes.inc is any more, but there was a fix for this `OP_HALT` bug in there as well - though a less assembly-based one:

https://github.com/prineside/sa-mp-fixes/blob/e772772f66ec51716239d66caaf6d3c3d405832f/fixes.inc#L5620-L5658

In both versions I call `heapspace()` - that's purely because a native call is required, any native really.  But since the bug is to do with the restoration of heap and stack, I felt that that was appropriate (it is also a very rarely used function AFAIK, and in the core PAWN functions, not just SA:MP).

**Comment by Patrik356b** [comment]
Would be nice if sa-mp would be using a newer vm version, but I'm not sure how much work switching version would involve

**Comment by Southclaw** [comment]
It's been discussed on the forum before, unfortunately it would break a lot of these weird little hacks along with some semantics (that I forgot, something to do with enums) most Pawn coders are happy with.

**Comment by Y-Less** [comment]
Actually, the older VM version isn't part of this problem.

**Comment by Y-Less** [comment]
Also, updating new a newer version of the 3.x VM wouldn't be a huge problem at all - within a major version everything is more-or-less backwards compatible.  The suggestion on the forum (at least the one I remember) was about moving to 4.x, which is a completely backwards-incompatible change - loads of new/changed syntax in the PAWN language, and a total overhaul to the VM and opcodes.  No existing code would compile, and no existing AMXs would run.  The pro argument was "but it is newer" (I assume they thought newer=better), the con argument was "it will break literally everything."

**Comment by Patrik356b** [comment]
Hence the 2nd part of my comment. (it's a bit like python 2 vs 3 actually)

**Comment by Y-Less** [comment]
A few changes:

```pawn
enum E_MY_THING
{
	A,
	B,
	C
}
```

Is now:

```pawn
const E_MY_THING // Old "const v = 8;" still works.
{
	A = 0, // Now explicit.
	B,
	C
}
```

```pawn
"unpacked"
!"packed"
```

Is now:

```pawn
''unpacked''
"packed"
```

```pawn
enum E_STRUCT
{
	A,
	B,
	C
}

new var[E_STRUCT];
```

Is now:

```pawn
new var[.A, .B, .C, .D];
```

They also changed `#define`, and I'm not at all sure how that will affect many things like `foreach`.

**Comment by PT-Player** [comment]
You Think that will solve the problem?

**Comment by Y-Less** [comment]
I didn't think any solutions had been offered yet.

**Comment by Southclaw** [comment]
Would it be possible/easy to do a compile-time flag that makes y_malloc use the old method? My compile is already ~100 seconds so more time wouldn't bother me.

**Comment by PT-Player** [comment]
I like the idea if that Solves the bug

**Comment by Y-Less** [comment]
Technically yes.

**Comment by Y-Less** [comment]
To elaborate.  y_malloc works by looking like an array.  Doing:

```pawn
new Alloc:c = malloc(10);
mget(c, 8);
```

Compiles as:

```pawn
new Alloc:c = malloc(10);
YSI_gMallocMemory[_:c + 8];
```

`YSI_gMallocMemory` is actually declared as `new YSI_gMallocMemory[1];`, and y_malloc just strips out every instance of `BOUNDS 0` in the resulting AMX (in case you compiled with debug information, people are unlikely to declare many 1-element arrays on purpose.  The removal of the bounds checking means that we can use any offset, and so the values returned by `malloc` include a huge offset, which means that this array access points outside of DAT and into HEA.  Making that array bigger and the `malloc` returned value smaller (to stay within the array bounds) should be pretty simple actually - much simpler than it was to go the other way in the first place.

**Comment by Y-Less** [comment]
Right, I've added a possible fix in Misiur/YSI-Includes#101; however, as I only had a theory as to the cause, and could never reproduce the issue myself, I have no idea if it actually works.  If someone could test it, that would be great.  Note that there are several other changes in that pull request (which you will need to integrate yourself for now - I can accept it but don't want to without more testing, though may because it is hidden behind the `YSI_NO_HEAP_MALLOC` compile-time option).  Most of the changes are additions or fixes, the only semantic change is with `Group_SetPlayerBalanced`, so watch out for that.

**Comment by Southclaw** [comment]
Groups aren't used in this project anyway so it should be no problem, thanks!

**Comment by Y-Less** [comment]
I merged the pull request, please let me know how it goes - this is a long-standing problem that I would love to get to the bottom of.  Most other bugs, even if I don't fix them, usually have some obvious (if hard) cause and solution in code.  This one - no clue!

**Comment by kadaradam** [comment]
I updated to the latest YSI, and the problem is still there. I'm trying to do more and more debugging. What do you think? Using defer with a string parameter, while initalizing the server can cause the dialogs not to work? Is there any connection between the 2 function?

**Comment by Y-Less** [comment]
None at all.  That was literally my only idea - did you use that compile flag?

**Comment by kadaradam** [comment]
Nah, did not see that. I recompiled with the flag, let's see.

**Comment by kadaradam** [comment]
I'm using recompiled version of the game for a week now, and looks like that fixed it.
Thanks!

**Comment by Y-Less** [comment]
Ahh good.  I still need to figure out why the heap version doesn't work, but I don't think that will be easy.  At least there is a solution.  How are your compile times?

**Comment by kadaradam** [comment]
Compile time is just fine, did not notice a lot of difference. However I noticed that there is an "Invalid memory access" error when this issue happens. I'll try to reproduce it, so you can fix the heap version.
